docs: Fix issues in readthedocs builds.
Add required .readthedocs.yml and docs/requirements.txt files.

Fixes error:
    NameError: name 'html_theme' is not defined

Also fixes a couple of issues highlighted by the sphinx build
output.